### ISSUE TITLE
[Idea] Add support for pip from yaml

### ISSUE THREAD

**Issue by p3likan0** [go-debos/debos#103]
Add option to install things with pip in yaml, I can imagine something like:

```
- action: pip
  version: 3
  packages:
      - pyserial
      - sarlanga
```
