### ISSUE TITLE
actions: download: Add support for integrity checks

### ISSUE THREAD

**Issue by ivy** [go-debos/debos#120]
When downloading files from remote URLs, it would be helpful to have some sort of integrity check to ensure the file wasn't corrupted or tampered with. To start, I'd consider adding a new key, `integrity`, accepting a `hash` to specify the algorithm and hex-encoded checksum:

```yaml
- action: download
  url: http://example.domain/path/filename.ext
  name: firmware
  integrity: 
    hash: sha256-5ecf8d2cc410094e8b82dd0bc178a57f3aa1e80916689beb00fe56148b1b1256
```

My reasoning for the nested struct/table is that it leaves this open for extension later, possibly adding support for GPG signatures.
