### ISSUE TITLE
Partition tables are not updated after ImagePartition / FilesystemDeploy

### ISSUE THREAD

**Issue by elboulangero** [go-debos/debos#154]
After deploying a filesystem, a quick look at `/dev/disk/by-id` shows that the kernel is not aware of the new partitions. This breaks tools that rely on that, for example `grub-probe` won't find the root partition as expected, and then `grub-mkconfig` won't be able to setup the kernel command-line with `root=UUID=...`. Instead it will fall back to `root=/dev/...`.

Workaround: One must manually run `partprobe`.

Suggestion: Debos could run partprobe by itself after creating the partitions?

----

Here's a quick recipe to illustrate this issue and the workaround:

```
{{- $suite := or .suite "stretch" -}}
  
architecture: amd64

actions:
  - action: debootstrap
    suite: {{ $suite }}
    components: [ main ]

  - action: apt
    packages: [ parted ]

  - action: image-partition
    imagename: {{ $suite }}.img
    imagesize: 2GB
    partitiontype: gpt
    partitions:
      - name: efi
        fs: fat32
        start: 0%
        end: 128MB
        flags: [ esp ]
      - name: boot
        fs: ext2
        start: 128MB
        end: 256MB
      - name: root
        fs: ext4
        start: 256MB
        end: 100%
    mountpoints:
      - mountpoint: /
        partition: root
      - mountpoint: /boot
        partition: boot
      - mountpoint: /efi
        partition: efi

  - action: run
    chroot: true
    command: ls -l /dev/disk/by-id

  - action: run
    chroot: true
    command: partprobe

  - action: run
    chroot: true
    command: ls -l /dev/disk/by-id
```

And the relevant part of debos output:

```
==== run ====
ls -l /dev/disk/by-id | total 0
ls -l /dev/disk/by-id | lrwxrwxrwx 1 root root 9 Apr 11 03:30 ata-QEMU_DVD-ROM_QM00003 -> ../../sr0
ls -l /dev/disk/by-id | lrwxrwxrwx 1 root root 9 Apr 11 03:30 virtio-fakedisk-0 -> ../../vda
==== run ====
==== run ====
ls -l /dev/disk/by-id | total 0
ls -l /dev/disk/by-id | lrwxrwxrwx 1 root root  9 Apr 11 03:30 ata-QEMU_DVD-ROM_QM00003 -> ../../sr0
ls -l /dev/disk/by-id | lrwxrwxrwx 1 root root  9 Apr 11 03:31 virtio-fakedisk-0 -> ../../vda
ls -l /dev/disk/by-id | lrwxrwxrwx 1 root root 10 Apr 11 03:31 virtio-fakedisk-0-part1 -> ../../vda1
ls -l /dev/disk/by-id | lrwxrwxrwx 1 root root 10 Apr 11 03:31 virtio-fakedisk-0-part2 -> ../../vda2
ls -l /dev/disk/by-id | lrwxrwxrwx 1 root root 10 Apr 11 03:31 virtio-fakedisk-0-part3 -> ../../vda3
```
