### ISSUE TITLE
filesystem uuid

### ISSUE THREAD

**Issue by Thompsion-tech** [go-debos/debos#174]
Hello. I have two problems.

Firstly, what is the correct way to specify the filesystem uuid? I have seen that the filesystem uuid is different for each building system image. 

Here is the part of target board yaml including rootfs uuid.
```
{{- $rootfs_uuid := or .rootfs_uuid "0f39fc7f-6616-4c91-b007-1374a6409511" -}} 

  - action: image-partition
    imagename: {{$image_name}}
    imagesize: {{$image_size}}
    partitiontype: {{$partition_type}}
    mountpoints:
      - mountpoint: /
        partition: rootfs
      - mountpoint: /boot
        partition: boot
        options: [ x-systemd.automount ]
    partitions:
...
      - name: rootfs
        fs: ext4
        start: {{$rootfs_partition_start}}
        end: 100%
        FSUUID: {{$rootfs_uuid}}
```

Secondly, Where can I get the Debootstrap Temporary files? I think that will help me to debug when I have some problems such as  `debootstrap.log | wget: unable to resolve host address`.

Thanks!
