### ISSUE TITLE
Deploying twice does not work

### ISSUE THREAD

**Issue by sangorrin** [go-debos/debos#176]
Hi,

It seems that you can only deploy the same file once while the actions' syntax suggests that you should be able to deploy them as many times as you want.

This is an example of an image with a redundant partition that can be used as a fallback filesystem or factory reset partition.

```
  - action: image-partition
    imagename: {{ $image }}
    imagesize: {{ $size }}
    partitiontype: gpt
    partitions:
      - name: EFI
        fs: fat32
        start: 0%
        end: 128MiB
        flags: [ esp ]
      - name: ROOTFSA
        fs: ext4
        start: 128MiB
        end: 1920MiB
      - name: ROOTFSB
        fs: ext4
        start: 1920MiB
        end: 3456MiB
    mountpoints:
      - mountpoint: /
        partition: ROOTFSA
        options: [ ro, noatime ]
      - mountpoint: /
        partition: ROOTFSB
        options: [ ro, noatime ]
      - mountpoint: /efi
        partition: EFI
        buildtime: true

  - action: filesystem-deploy
    description: Deploying filesystem onto image
```

In other words, the contents of "/" should be deployed to both partitions ROOTFSA and ROOTFSB. Unfortunately, the current behavior is that ROOTFSB remains empty.

Thanks,
Daniel
