### ISSUE TITLE
Filesystem-deploy should contain more information

### ISSUE THREAD

**Issue by sangorrin** [go-debos/debos#178]
I think that the action filesystem-deploy should contain information about how to deploy the chroot contents into the partitions (mountpoints should be used only to define fstab). For example, something like this:

```
  - action: filesystem-deploy
    description: Deploying filesystem onto image
    partitions:
      - name: EFI
        files: /efi
      - name: ROOTFS
        files: /
        blacklist: /efi, /var
      - name: FACTORYRESET
        files: /
      - name: VAR
        files: /var
```

Also, mountpoints should have its own action, separated from image-partition. This will allow, specifying mountpoints for multiple rootfs partitions (e.g., factory reset rootfs, A/B software updates rootfs, chrootfs, ...)

```
- action: mountpoints
  root-partitions: 
      - name: ROOTFS
        mountpoints:
          - mountpoint: /
	       partition: ROOTFS
          - mountpoint: /var
	       partition: VAR
      - name: FACTORYRESET
          - mountpoint: /
	       partition: FACTORYRESET
```

Also these options should be removed from filesystem-deploy and put into the mountpoints action so that we can generate fstab/cmdline on each root partition.
- setup-fstab: bool
- setup-kernel-cmdline: bool
- append-kernel-cmdline: arguments

Thanks,
Daniel
