### ISSUE TITLE
Weird problem with /etc/localtime

### ISSUE THREAD

**Issue by sangorrin** [go-debos/debos#180]
Hi,

I don't know why but some part of Debos (perhaps) does not seem to like /etc/localtime. The problem can be reproduced with this sort YAML (the original one was using dpkg-reconfigure tzdata but this one is simpler). I create two symbolic links (`/etc/localtime` and `/etc/localtime_b`), both of them pointing to the same file (`/usr/share/zoneinfo/Asia/Tokyo`) which belongs to `tzdata` and is included in `debootstrap`. After that, I list the files in `/etc` and for some reason that I can't understand `/etc/localtime` disappears while `/etc/localtime_b` persists.

```
{{- $architecture := or .architecture "amd64" -}}
{{- $suite := or .suite "buster" -}}

architecture: {{ $architecture }}

actions:
  - action: debootstrap
    description: create Debian filesystem base
    suite: {{ $suite }}
    components: [ main ]
    mirror: http://ftp.jaist.ac.jp/pub/Linux/debian

  - action: run
    description: create link to localtime
    chroot: true
    command: ln -s /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

  - action: run
    description: create link to localtime
    chroot: true
    command: ln -s /usr/share/zoneinfo/Asia/Tokyo /etc/localtime_b

  - action: run
    description: check link to localtime
    chroot: true
    command: ls -l /etc
```

Thanks,
Daniel
