### ISSUE TITLE
docker image: not able to start any command in debug shell

### ISSUE THREAD

**Issue by d4s** [go-debos/debos#191]
With current docker image it is not possible to get working debug shell.
If error acquired and debug  option `--debug-shell` is set, the debos show the bash-5 prompt and stuck forever after any command typed.

Simple recipe to reproduce:
```
architecture: amd64

actions:

  - action: run
    description: Failed action
    chroot: false
    command: false
```
