### ISSUE TITLE
Swap partition

### ISSUE THREAD

**Issue by chellem** [go-debos/debos#209]
Hi,

May I know how can I create a swap partition?

I've tried:

```yml
    mountpoints:
      - mountpoint: /dev/swap
      partition: swap
    partitions:
      - name: swap
        fs: swap
        start: 0%
        end: 2048MB


But it's throwing an error.

**Comment by obbardc** [comment]
what's the error?

**Comment by obbardc** [comment]
in most cases we've been creating swapfiles rather than complete partitions: https://linuxize.com/post/how-to-add-swap-space-on-debian-10/

i guess we just haven't hit this error yet :-)

**Comment by jonathanjsimon** [comment]
@obbardc Very good idea, I'll do that in the meantime. Thanks!

**Comment by jonathanjsimon** [comment]
For anybody else looking for a solution, I took the method in @obbardc's link and integrated it into my debos recipe just before packaging and it did work. The grep call might be unnecessary.

In a script:
```shell
#!/bin/sh

fallocate -l 1G /swapfile
chmod 600 /swapfile
mkswap /swapfile

if [ `grep -c swapfile /etc/fstab` -eq 0 ]
then
    echo "/swapfile swap swap defaults 0 0" >> /etc/fstab
fi
```

In the recipe:

```yaml
  - action: run
    chroot: true
    script: scripts/configure_swap.sh
```

**Comment by elboulangero** [comment]
If you really needs a swap **partition**, you can also create a partition with a `none` filesystem, then set it up yourself with a script.

For example, in the recipe:

```
    partitions:
      - name: swap
        fs: none
        start: 2048s
        end: 1GB
        flags: [ swap ]

  [...]

  - action: filesystem-deploy

  - action: run
    chroot: true
    script: scripts/setup-swap.sh
```

Then the `setup-swap.sh` script:

```
#!/bin/sh

N=1

mkswap -L swap ${IMAGE}-part${N}
UUID=$(swaplabel ${IMAGE}-part${N} | grep ^UUID: | awk '{print $2}')
echo "UUID=${UUID} none swap defaults 0 0" >> /etc/fstab
```

Replace `N=1` by the number of your actual swap partition, of course.
