### ISSUE TITLE
ImagePartition Partition Features key is case-sensitive

### ISSUE THREAD

**Issue by UniversalSuperBox** [go-debos/debos#215]
After running into https://github.com/go-debos/debos/issues/78, I noticed the `features` key on a partition in `image-partition` could be used to disable features at will.

However, when I tried to use the option, I received the following output:

```
./debos-docker -e http_proxy:http://192.168.88.101:3128 -m 5G --debug-shell test.yaml
2020/06/01 22:18:23 Action `image-partition` failed at stage Verify, error: Couldn't find partition for /
```

This continued until I made the `features:` key in my partition entry uppercase, after which the recipe worked correctly:

```
./debos-docker -e http_proxy:http://192.168.88.101:3128 -m 5G --debug-shell test.yaml
Running /debos --artifactdir /recipes --environ-var http_proxy:"http://192.168.88.101:3128" /recipes/test.yaml --debug-shell --shell /bin/bash --internal-image /dev/disk/by-id/virtio-fakedisk-0
2020/06/01 22:18:39 ==== image-partition ====
2020/06/01 22:18:40 Formatting partition 1 | mke2fs 1.44.5 (15-Dec-2018)
[...]
```

Here is a minimal example recipe which can reproduce this problem:

```yaml
{{- $architecture := or .architecture "amd64" -}}
{{- $image := or .image "test.img" -}}

architecture: {{ $architecture }}
actions:
  - action: image-partition
    imagename: {{ $image }}
    imagesize: 4M
    partitiontype: gpt
    mountpoints:
      - mountpoint: /
        partition: root

    partitions:
      - name: root
        fs: ext4
        start: 1M
        end: 100%
        features: "^metadata_csum"
```

**Comment by UniversalSuperBox** [comment]
This was my misunderstanding of yaml syntax. `String[]` cannot be specified as a single string, they *must* be specified as lists. For a fixed example...

```
{{- $architecture := or .architecture "amd64" -}}
{{- $image := or .image "test.img" -}}

architecture: {{ $architecture }}
actions:
  - action: image-partition
    imagename: {{ $image }}
    imagesize: 4M
    partitiontype: gpt
    mountpoints:
      - mountpoint: /
        partition: root

    partitions:
      - name: root
        fs: ext4
        start: 1M
        end: 100%
        features: 
          - "^metadata_csum"
```
