### ISSUE TITLE
Multi-line run action does not check for |

### ISSUE THREAD

**Issue by evelikov** [go-debos/debos#289]
Currently debos does not warn nor error on instances where "|" is missing for a multi-line `run` action.  That combined with the fact that the a) command is not printed and b) stderr is hidden in the Gitlab CI webUI  (as commonly used) makes for a very fragile solution. Ideally it will be part of a lint stage, validating the yaml.

Reproducer:
```
architecture: amd64

actions:
  - action: run
    description: NAAAAAAAAAAME
    chroot: false
    command: <<< note the missing |
      uname -a
      echo foo
```
