### ISSUE TITLE
Multi-line run action, does not error out if individual command fails

### ISSUE THREAD

**Issue by evelikov** [go-debos/debos#290]
When using a multi-line run action - we continue execution, even if the command has failed. At the same time, for single-line instance - we error-out.

IMHO we should be looking for consistent behaviour across the two.

Reproducer:
```
architecture: amd64

actions:
  - action: run
    description: Hello world
    chroot: false
    command: |
      false
      echo "Prior command failed, yet execution continues..."
```
