### ISSUE TITLE
Support creating extend and logical partitions in case of msdos

### ISSUE THREAD

**Issue by daichifukui** [go-debos/debos#293]
Hi.

In case the partition type is msdos, debos always set the partition label to primary for parted.
However, `parted` as such supports not only primary but extended and logical as a partition label.
Someone may still want to use msdos due to their limitation of BIOS, firmware or hardware.

If it makes sense, can you consider adding the extended and logical support?

Based on the background mentioned above, I have created a patch for this. 

https://github.com/daichifukui/debos/commit/5a38a0bb78b50a99755224ce6596b5ea946e0cd7

The mechanism is that if the number of partitions is more than 4, 3 of them are automatically created as primary, 1 of them is extended, and the remaining partitions are logical.  
If the number is less than or equal to 4, all of the partitions are created as primary.  

This patch was tested with the following two partition layouts. Both of the patterns worked fine.  

**CASE1**: 4 partitions (all of them are supposed to be primary):  
<details>
<summary> Partition layout case1 (click me to expand) </summary>

```
  - action: image-partition
    description: "Creating RW partitions"
    imagename: {{ $imagename }}
    imagesize: {{ $imagesize }}
    partitiontype: msdos
    ptuuid: {{ $ptuuid }}
    partitions:
      - name: BIOS
        fs: fat32
        start: 1MiB
        end: 2MiB
        partuuid: {{ $bios_partuuid }}
      - name: EFI
        fs: fat32
        start: 2MiB
        end: 130MiB
        partuuid: {{ $efi_partuuid }}
        fsuuid: {{ $efi_fsuuid }}
      - name: ROOTFS
        fs: {{ $filesystem }}
        start: 130MiB
        end: 90%
        partuuid: {{ $rootfs_partuuid }}
        fsuuid: {{ $rootfs_fsuuid }}
      - name: ROOTFS2
        fs: {{ $filesystem }}
        start: 90%
        end: 95%
```

</details>

**CASE2**: 5 partitions (Partitions are supposed to be 3 primary ones, 1 extended one, 1 logical one):  
<details>
<summary> Partition layout case2 (click me to expand) </summary>

```
  - action: image-partition
    description: "Creating RW partitions"
    imagename: {{ $imagename }}
    imagesize: {{ $imagesize }}
    partitiontype: msdos
    ptuuid: {{ $ptuuid }}
    partitions:
      - name: BIOS
        fs: fat32
        start: 1MiB
        end: 2MiB
        partuuid: {{ $bios_partuuid }}
      - name: EFI
        fs: fat32
        start: 2MiB
        end: 130MiB
        partuuid: {{ $efi_partuuid }}
        fsuuid: {{ $efi_fsuuid }}
      - name: ROOTFS
        fs: {{ $filesystem }}
        start: 130MiB
        end: 90%
        partuuid: {{ $rootfs_partuuid }}
        fsuuid: {{ $rootfs_fsuuid }}
      - name: ROOTFS2
        fs: {{ $filesystem }}
        start: 90%
        end: 95%
      - name: ROOTFS3
        fs: {{ $filesystem }}
        start: 95%
        end: 100%
```

</details>

Feedback is welcome.  
If there is no objection, I would like to send a pull request regarding this issue.

Best regards,
Fukui
