### ISSUE TITLE
Debos silently accepts invalid action attributes

### ISSUE THREAD

**Issue by evelikov** [go-debos/debos#295]
Consider the following example:

```
architecture: amd64

actions:
  - action: run
    description: Name
    chrot: false
    command: echo test

```

In the above example we've made a typo in the optional argument `chroot` -> `chrot`. One would expect that debos will parse and warn (fail even) on the chrot line, yet that's not the case. Mind you, this can be kept as opt-in toggle (when running debos), although debos should really verify and catch trivial human errors. We all make typos, some of use are even dyslexic.
