### ISSUE TITLE
The working directory will be set to the artifact directory

### ISSUE THREAD

**Issue by elboulangero** [go-debos/debos#345]
This is what is documented in https://pkg.go.dev/github.com/go-debos/debos/actions#hdr-Run_Action:

> - postprocess -- if set script or command is executed after all other commands and has access to the recipe directory ($RECIPEDIR) and the artifact directory ($ARTIFACTDIR). The working directory will be set to the artifact directory. 

In practice, it doesn't seem to be true, the working directory seem to be RECIPEDIR in any case.

Recipe:

```
architecture: amd64

actions:
  - action: run
    postprocess: true
    command: pwd
```

Output:

```
$ debos recipe.yaml 
[...]
2022/05/30 12:34:03 pwd | /home/me/recipes
[...]

$ mkdir d
$ debos --artifactdir=d recipe.yaml 
[...]
2022/05/30 12:34:31 pwd | /home/me/recipes
[...]
```
