### ISSUE TITLE
parted | Error: The location 32768 is outside of the device /dev/vda.

### ISSUE THREAD

**Issue by CounterPillow** [go-debos/debos#385]
Thanks for debos, it is very useful.

I'm getting `parted | Error: The location 32768 is outside of the device /dev/vda.` when trying to use the image-partition action.

Steps to reproduce:
```yaml
  - action: image-partition
    description: Partition image
    imagename: {{ $image }}
    imagesize: 2GB
    partitiontype: gpt
    mountpoints:
      - mountpoint: /
        partition: root
        options:
          - 'x-systemd.growfs'
    partitions:
      - name: idbloader
        fs: none
        start: {{ sector 64 }}
        end: {{ sector 16384 }}
      - name: uboot
        fs: none
        start: {{ sector 16384 }}
        end: {{ sector 65536 }}
      - name: root
        fs: ext4
        start: {{ sector 65536 }}
        end: 100%
        parttype: b921b045-1df0-41c3-af44-4c6f280d3fae  # ARM 64 root type
```

64 * 512 = 32768 so I assume idbloader is the problem here, but I don't know if I'm doing something naughty gpt won't allow or if debos is bugging out. rockchip maskrom requires SPL to be at 32768 so I can't do anything about that.

**Comment by CounterPillow** [comment]
Nevermind, I ran into parted nonsense. The start/end properties are mostly passed on as-is. Turns out that you need to specify a unit, so in this case:

```yaml
  - action: image-partition
    description: Partition image
    imagename: {{ $image }}
    imagesize: 2GB
    partitiontype: gpt
    mountpoints:
      - mountpoint: /
        partition: root
        options:
          - 'x-systemd.growfs'
    partitions:
      - name: idbloader
        fs: none
        start: 64s
        end: 16383s
      - name: uboot
        fs: none
        start: 16384s
        end: 65535s
      - name: root
        fs: ext4
        start: 65536s
        end: 100%
        parttype: b921b045-1df0-41c3-af44-4c6f280d3fae  # ARM 64 root type
```

Note the `s` after the `{{ sector n }}`. (Also, adjust the sector ends to not overlap, classic off-by-one)
