### ISSUE TITLE
Test continuously fails: Failed to mount /usr/lib/os-release (type n/a)

### ISSUE THREAD

**Issue by tripleo1** [go-debos/debos#407]
Input:
```
# cd test/debian
# debos test.yaml
```

Output:
```
2023/05/07 22:01:23 Debootstrap | I: Unpacking the base system...
2023/05/07 22:01:23 Debootstrap | I: Base system installed successfully.
2023/05/07 22:01:23 apt clean | Failed to mount /usr/lib/os-release (type n/a) on /scratch/root/run/host/os-release (MS_BIND ""): No such file or directory
2023/05/07 22:01:23 Action `debootstrap` failed at stage Run, error: exit status 1
Powering off.
```

**Comment by tripleo1** [comment]
Findings:

1. Git version compiled with debian packaged go will reproduce the above 
2. May be related to fakemachine
3. Debian packaged debos works with the following

```
{{ $architecture := or .architecture "amd64" }}
{{ $suite := or .suite "bullseye" }}
{{ $image := or .image (printf "debian-example-ospack-%s-%s.tar.gz" $suite $architecture) }}

architecture: {{ $architecture }}

actions:
  - action: debootstrap
    suite: {{ $suite }}
    components:
      - main
    mirror: https://deb.debian.org/debian
    variant: minbase

  - action: apt
    description: Install some packages
    packages:
      - sudo
      - openssh-server
      - adduser
      - systemd-sysv

  - action: run
    chroot: true
    script: scripts/setup-user.sh

  - action: overlay
    source: overlays/sudo

  - action: run
    command: echo debian > ${ROOTDIR}/etc/hostname

  - action: pack
    file: {{ $image }}
    compression: gz

  - action: ostree-commit
    repository: ostree
    branch: demo

```
