### ISSUE TITLE
Explicit partuuid is not updating in final image

### ISSUE THREAD

**Issue by openedev** [go-debos/debos#447]
I did install debos via apt-get on my bullseye docker and trying to create image with arm64 GPT root filesystem partuuid for 'rootfs' partition as mentioned below.

```
  - action: image-partition
    imagename: {{ $image }}.img
    imagesize: {{$imagesize}}
    partitiontype: gpt
    mountpoints:
      - mountpoint: /
        partition: rootfs
      - mountpoint: /boot
        partition: boot
        options: [ x-systemd.automount ]
    partitions:
      - name: loader1
        fs: none
        start: 64s
        end: 7168s
      - name: loader2
        fs: none
        start: 16384s
        end: 24575s
      - name: boot
        fs: fat32
        start: 32768S
        end: 1081343S
        flags: [ boot, esp ]
      - name: rootfs
        fs: ext4
        start: 1081344S
        end: 100%
        partuuid: b921b045-1df0-41c3-af44-4c6f280d3fae
```

I did tried with capital letter strings and even with "" but none seems not working. It is showing different PARTUUID.

```
$ sudo blkid /dev/loop30p4 
/dev/loop30p4: LABEL="rootfs" UUID="3e70dbb5-d80d-45c7-8cc5-55cc46e8e085" TYPE="ext4" PARTLABEL="rootfs" PARTUUID="1f196b2e-c42a-409b-8cdf-979e3b660e07"
```

Any help?
