### ISSUE TITLE
Option for partition mountpoint does not appeared in `/etc/fstab`

### ISSUE THREAD

**Issue by d4s** [go-debos/debos#74]
Option for mountpoint is ignored. For example:
```
  - action: image-partition
    imagename: {{ $image }}.img
    mountpoints:
      - mountpoint: /
        partition: system
        flags: [ boot ]
        options: ro
```
