### ISSUE TITLE
actions: image-partition: add support for Partition Type GUIDs

### ISSUE THREAD

**Issue by elboulangero** [go-debos/debos#98]
[Partition Type GUIDs](https://en.wikipedia.org/wiki/GUID_Partition_Table#Partition_type_GUIDs) are used to identify GPT partitions.

They are at the core of the [Discoverable Partition Spec](https://www.freedesktop.org/wiki/Specifications/DiscoverablePartitionsSpec/), which is implemented by [systemd-auto-gpt-generator](http://www.freedesktop.org/software/systemd/man/systemd-gpt-auto-generator.html). This generator can't work without it.

Right now I set these *Partition Type GUIDs* through a post-process step such as:

```
  # EFI System Partition
  - action: run
    postprocess: true
    command: /sbin/sfdisk --part-type image.img 1 c12a7328-f81f-11d2-ba4b-00a0c93ec93b
```

It would be nice to have it supported in the `image-partition` action though, with something like:

```
  partitions:
    - name: label
    - part-type: c12a7328-f81f-11d2-ba4b-00a0c93ec93b
      ...
```

Is it something that you would like to support in debos?

**Comment by elboulangero** [comment]
Hey, would you accept a patch for that? That would be nice to have a reply.

**Comment by obbardc** [comment]
this would be a great feature; it would also be good to add the GUID mapping inside debos so you could do something like:

```
  partitions:
    - name: label
    - partition-type: GUID.Linux.LinuxFilesystemData
```

**Comment by elboulangero** [comment]
Otherwise you can leverage the Go templating langage and do something like that:

```
# GPT GUID definitions, for the sake of clarity. For details refer to:
# https://www.freedesktop.org/wiki/Specifications/DiscoverablePartitionsSpec
{{ $efi_system_partition := "c12a7328-f81f-11d2-ba4b-00a0c93ec93b" }}
...

    partitions:
      - type: {{ $efi_system_partition }}
        name: esp
```

But yeah if Debos could provide aliases for common type GUIDs, that would be even better.
